# Generated by Django 2.2.5 on 2021-05-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('publish', 'publish'), ('draft', 'draft')], default='draft', max_length=8),
        ),
    ]
